// GENERATED by scripts/brand-paths.mjs from public/brand/ — do not edit; run `npm run brand:paths`.
// B51: the viewBox and size of each brand drawing, for <BrandMark>/<BrandWordmark> (client-safe: no path data).
export const brandBoxes = {
  mark: {
    "file": "logo-mark.svg",
    "viewBox": "282.0 162.0 735.5 670.5",
    "width": 735.5,
    "height": 670.5
  },
  wordmark: {
    "file": "wordmark.svg",
    "viewBox": "147.0 874.0 1018.5 216.5",
    "width": 1018.5,
    "height": 216.5
  },
} as const
