#!/usr/bin/env node
/**
 * B51 — generate components/brand/brandPaths.generated.ts from the brand
 * files in public/brand/ (the static site's copies, byte for byte — see
 * tests/lib/brandParity.test.ts). The mark and the wordmark are each one
 * `currentColor` path; this keeps their viewBox and path data in a module
 * the server-rendered <BrandSymbols> inlines once per page, so the hero,
 * the watermark and the header draw them with `<use href="#brand-…">`:
 * no request, no loader dependency, no path data in the client bundle.
 *
 *   node scripts/brand-paths.mjs          # rewrite the module
 *   node scripts/brand-paths.mjs --check  # exit 1 if it differs (the test runs this)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'components', 'brand', 'brandPaths.generated.ts');
const FILES = { mark: 'logo-mark.svg', wordmark: 'wordmark.svg' };

export function parseBrandSvg(svg, name) {
  const viewBox = svg.match(/<svg[^>]*\sviewBox="([^"]+)"/)?.[1];
  const paths = [...svg.matchAll(/<path\b([^>]*)\/?>/g)];
  if (!viewBox || paths.length !== 1) throw new Error(`${name}: expected one <path> and a viewBox`);
  const attrs = paths[0][1];
  const d = attrs.match(/\sd="([^"]+)"/)?.[1];
  const fillRule = attrs.match(/\sfill-rule="([^"]+)"/)?.[1] ?? 'nonzero';
  if (!d || !/\sfill="currentColor"/.test(attrs)) throw new Error(`${name}: the path must be fill="currentColor" with a d`);
  const [, , w, h] = viewBox.split(/\s+/).map(Number);
  return { viewBox, width: w, height: h, fillRule, d };
}

export function render() {
  const entries = Object.entries(FILES).map(([key, file]) => {
    const parsed = parseBrandSvg(readFileSync(join(ROOT, 'public', 'brand', file), 'utf8'), file);
    return `  ${key}: ${JSON.stringify({ file, ...parsed }, null, 2).replace(/\n/g, '\n  ')},`;
  });
  return `// GENERATED by scripts/brand-paths.mjs from public/brand/ — do not edit; run \`npm run brand:paths\`.\n// B51: the brand mark and wordmark as path data for <BrandSymbols>.\nexport const brandPaths = {\n${entries.join('\n')}\n} as const\n`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const next = render();
  if (process.argv.includes('--check')) {
    let current = '';
    try { current = readFileSync(OUT, 'utf8'); } catch { /* missing counts as different */ }
    if (current !== next) {
      console.error('components/brand/brandPaths.generated.ts is out of date: run `npm run brand:paths` and commit.');
      process.exit(1);
    }
    console.log('brandPaths.generated.ts is up to date');
  } else {
    writeFileSync(OUT, next);
    console.log(`wrote ${OUT}`);
  }
}
