#!/usr/bin/env node
/**
 * B51 — generate the brand modules from the brand files in public/brand/
 * (the static site's copies, byte for byte — see tests/lib/brandParity.test.ts).
 * The mark and the wordmark are each one `currentColor` path. The
 * server-rendered <BrandSymbols> inlines them once per page, so the hero, the
 * watermark and the header draw them with `<use href="#brand-…">`: no request,
 * no loader dependency.
 *
 * Two modules, because the drawers are client components: the path data goes
 * to brandPaths.generated.ts, imported only by the server component (never
 * bundled for the browser), and the sizes to brandBoxes.generated.ts for
 * <BrandMark>/<BrandWordmark> — the first version had the components import
 * the paths and the landing's JavaScript grew by 13 KB.
 *
 *   node scripts/brand-paths.mjs          # rewrite both modules
 *   node scripts/brand-paths.mjs --check  # exit 1 if either differs (the test runs this)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_PATHS = join(ROOT, 'components', 'brand', 'brandPaths.generated.ts');
const OUT_BOXES = join(ROOT, 'components', 'brand', 'brandBoxes.generated.ts');
const FILES = { mark: 'logo-mark.svg', wordmark: 'wordmark.svg' };
const HEADER = '// GENERATED by scripts/brand-paths.mjs from public/brand/ — do not edit; run `npm run brand:paths`.\n';

export function parseBrandSvg(svg, name) {
  const viewBox = svg.match(/<svg[^>]*\sviewBox="([^"]+)"/)?.[1];
  const paths = [...svg.matchAll(/<path\b([^>]*)\/?>/g)];
  if (!viewBox || paths.length !== 1) throw new Error(`${name}: expected one <path> and a viewBox`);
  const attrs = paths[0][1];
  const d = attrs.match(/\sd="([^"]+)"/)?.[1];
  const fillRule = attrs.match(/\sfill-rule="([^"]+)"/)?.[1] ?? 'nonzero';
  if (!d || !/\sfill="currentColor"/.test(attrs)) throw new Error(`${name}: the path must be fill="currentColor" with a d`);
  const [, , w, h] = viewBox.split(/\s+/).map(Number);
  return { viewBox, width: w, height: h, fillRule, d };
}

export function render() {
  const parsed = Object.fromEntries(
    Object.entries(FILES).map(([key, file]) => [key, { file, ...parseBrandSvg(readFileSync(join(ROOT, 'public', 'brand', file), 'utf8'), file) }]),
  );
  const block = (name, pick) =>
    `export const ${name} = {\n${Object.entries(parsed)
      .map(([key, value]) => `  ${key}: ${JSON.stringify(pick(value), null, 2).replace(/\n/g, '\n  ')},`)
      .join('\n')}\n} as const\n`;
  return {
    paths: `${HEADER}// B51: the brand mark and wordmark as path data for <BrandSymbols> — a server component; never import this from a client component.\n${block('brandPaths', (v) => v)}`,
    boxes: `${HEADER}// B51: the viewBox and size of each brand drawing, for <BrandMark>/<BrandWordmark> (client-safe: no path data).\n${block('brandBoxes', ({ file, viewBox, width, height }) => ({ file, viewBox, width, height }))}`,
  };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const next = render();
  const targets = [[OUT_PATHS, next.paths], [OUT_BOXES, next.boxes]];
  if (process.argv.includes('--check')) {
    for (const [out, content] of targets) {
      let current = '';
      try { current = readFileSync(out, 'utf8'); } catch { /* missing counts as different */ }
      if (current !== content) {
        console.error(`${out} is out of date: run \`npm run brand:paths\` and commit.`);
        process.exit(1);
      }
    }
    console.log('brandPaths.generated.ts and brandBoxes.generated.ts are up to date');
  } else {
    for (const [out, content] of targets) {
      writeFileSync(out, content);
      console.log(`wrote ${out}`);
    }
  }
}
