"""recurring booking series

Revision ID: 0002_recurring_bookings
Revises: 0001_baseline_schema
Create Date: 2026-09-02

Adds `recurrence_rules` (the source of truth for a series) and the nullable
`bookings.recurrence_rule_id` back-reference. Occurrences stay ordinary
`bookings` rows — flat expansion, nothing computed on read — so the
`bookings_no_overlap` EXCLUDE constraint from 0001 keeps arbitrating slots for
series bookings without any change.

Autogenerated, then adjusted in two places `--autogenerate` gets wrong:

- the foreign key was emitted unnamed, which makes the downgrade's
  `drop_constraint(None, ...)` unrunnable. It is named explicitly here.
- `recurrence_frequency` is created implicitly by `create_table` but is not
  dropped by `drop_table` (alembic reflects a bare Table, so SQLAlchemy's ENUM
  drop hook never fires). The downgrade drops it by hand, the same way 0001
  does, otherwise a downgrade→upgrade round-trip dies with DuplicateObjectError
  and the migrations workflow's leftover-enum check fails.

"""
from alembic import op
import sqlalchemy as sa


# Keep revision ids <= 32 chars: alembic's alembic_version.version_num is
# varchar(32) and a longer id fails to stamp with StringDataRightTruncationError.
revision = '0002_recurring_bookings'
down_revision = '0001_baseline_schema'
branch_labels = None
depends_on = None

FK_BOOKINGS_RECURRENCE = "fk_bookings_recurrence_rule_id"


def upgrade() -> None:
    op.create_table('recurrence_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('frequency', sa.Enum('weekly', name='recurrence_frequency'), server_default='weekly', nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('until_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recurrence_rules_org_id_is_active', 'recurrence_rules', ['org_id', 'is_active'], unique=False)
    op.create_index('ix_recurrence_rules_room_id', 'recurrence_rules', ['room_id'], unique=False)
    op.create_index('ix_recurrence_rules_user_id', 'recurrence_rules', ['user_id'], unique=False)

    op.add_column('bookings', sa.Column('recurrence_rule_id', sa.UUID(), nullable=True))
    op.create_index('ix_bookings_recurrence_rule_id', 'bookings', ['recurrence_rule_id'], unique=False)
    # SET NULL, not CASCADE: retiring a series flips `is_active`, and if a rule
    # is ever deleted outright the occurrences that already happened must
    # survive as ordinary bookings rather than vanish from the record.
    op.create_foreign_key(
        FK_BOOKINGS_RECURRENCE,
        'bookings',
        'recurrence_rules',
        ['recurrence_rule_id'],
        ['id'],
        ondelete='SET NULL',
    )


def downgrade() -> None:
    op.drop_constraint(FK_BOOKINGS_RECURRENCE, 'bookings', type_='foreignkey')
    op.drop_index('ix_bookings_recurrence_rule_id', table_name='bookings')
    op.drop_column('bookings', 'recurrence_rule_id')

    op.drop_index('ix_recurrence_rules_user_id', table_name='recurrence_rules')
    op.drop_index('ix_recurrence_rules_room_id', table_name='recurrence_rules')
    op.drop_index('ix_recurrence_rules_org_id_is_active', table_name='recurrence_rules')
    op.drop_table('recurrence_rules')

    op.execute("DROP TYPE recurrence_frequency")
